blank_issues_enabled: true
contact_links:
  - name: 🤔 Questions and Help
    url: https://github.com/ahaywood/lemon-lime-svgs/discussions
    about: Please ask and answer questions here.
  - name: 💬 General Discussion
    url: https://github.com/ahaywood/lemon-lime-svgs/discussions
    about: For general discussions about Lemon Lime SVGs.